import path from "path";
import { analyzeRepo } from "../services/analyzer";
import { generateConfigs } from "../services/generator";
import { createPullRequest, getRepo } from "../services/github";
import { checkoutBranch, cloneRepo, commitFiles, isGitRepo, pushBranch } from "../services/git";
import { ensureDir } from "../utils/fs";
import { parseRepoIdentifier } from "../utils/validation";

type PrOptions = {
  branch?: string;
};

export async function prCommand(repo: string | undefined, options: PrOptions): Promise<void> {
  if (!repo) {
    console.error("Provide a repo in owner/name form.");
    process.exitCode = 1;
    return;
  }

  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  if (!token) {
    console.error("Set GITHUB_TOKEN or GH_TOKEN to use PR automation.");
    process.exitCode = 1;
    return;
  }

  const parsed = parseRepoIdentifier(repo);
  if (!parsed) {
    console.error("Invalid repo format. Use owner/name with valid GitHub names.");
    process.exitCode = 1;
    return;
  }
  const { owner, name } = parsed;

  const repoInfo = await getRepo(token, owner, name);
  const cacheRoot = path.join(process.cwd(), ".primer-cache");
  const repoPath = path.join(cacheRoot, owner, name);
  await ensureDir(repoPath);

  if (!(await isGitRepo(repoPath))) {
    await cloneRepo(repoInfo.cloneUrl, repoPath);
  }

  const branch = options.branch ?? "primer/add-configs";
  await checkoutBranch(repoPath, branch);

  const analysis = await analyzeRepo(repoPath);
  await generateConfigs({
    repoPath,
    analysis,
    selections: ["mcp", "vscode"],
    force: true
  });

  await commitFiles(repoPath, [".vscode/settings.json", ".vscode/mcp.json"], "chore: add AI configurations via Primer");
  await pushBranch(repoPath, branch);

  const prUrl = await createPullRequest({
    token,
    owner,
    repo: name,
    title: "🤖 Prime this repo for AI",
    body: buildPrBody(),
    head: `${owner}:${branch}`,
    base: repoInfo.defaultBranch
  });

  console.log(`Created PR: ${prUrl}`);
}

function buildPrBody(): string {
  return [
    "## 🤖 Primed for AI",
    "",
    "This PR adds configurations to prime this repository for AI coding assistants.",
    "",
    "### Added Files",
    "",
    "| File | Purpose |",
    "|------|---------|",
    "| `.vscode/settings.json` | VS Code settings for optimal AI assistance |",
    "| `.vscode/mcp.json` | Model Context Protocol server configuration |",
    "",
    "### How to Use",
    "",
    "1. Merge this PR",
    "2. Open the project in VS Code",
    "3. Start chatting with Copilot — it now understands your project!",
    "",
    "---",
    "*Generated by Primer*"
  ].join("\n");
}
